[package]
name = "annealer"
version = "0.1.0"
edition = "2021"

[lib]
name = "annealer"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0.86"
csv = "1.3.0"
dbase = "0.5.0"
geo = "0.28.0"
itertools = "0.13.0"
nalgebra = "0.33.0"
pyo3 = "0.22.2"
serde_json = "1.0.125"
shapefile = "0.6.0"
