[package]
name = "annealer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "annealer"
crate-type = ["cdylib"]

[dependencies]
itertools = "0.13.0"
log = "0.4.22"
pyo3 = "0.21.1"
pyo3-log = "0.11.0"
